# Generated by Django 5.2 on 2025-04-14 01:20

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bingo_room', '0002_bingocard'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='RoomParticipant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('joined_at', models.DateTimeField(auto_now_add=True)),
                ('room', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='participants', to='bingo_room.bingoroom')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='current_room', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
