# Generated by Django 5.2 on 2025-04-15 17:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bingo_room', '0003_roomparticipant'),
    ]

    operations = [
        migrations.AddField(
            model_name='bingoroom',
            name='is_closed',
            field=models.BooleanField(default=False),
        ),
    ]
