# Generated by Django 5.2 on 2025-04-14 02:11

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bingo_room', '0003_roomparticipant'),
        ('game_session', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='gamesession',
            name='winner',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='won_sessions', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='gamesession',
            name='winning_card',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='winning_sessions', to='bingo_room.bingocard'),
        ),
        migrations.CreateModel(
            name='GameHistory',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('room_code', models.CharField(max_length=10)),
                ('winning_card_hash', models.CharField(blank=True, max_length=64, null=True)),
                ('drawn_numbers', models.JSONField()),
                ('started_at', models.DateTimeField()),
                ('ended_at', models.DateTimeField(auto_now_add=True)),
                ('is_completed', models.BooleanField(default=True)),
                ('session', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='history', to='game_session.gamesession')),
                ('winner', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='victory_history', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-ended_at'],
            },
        ),
    ]
