# Generated by Django 5.2 on 2025-04-15 19:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_rename_nickname_user_username'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='is_admin',
        ),
    ]
